### ISSUE TITLE
Clarify Messages

### ISSUE THREAD

**Issue by TheDarkLordSano** [TheDarkLordSano/HFYBeetusBot#15]
The bot currently replies after a subscribe or unsubscribe with a list of current subscriptions.

People are confused about it.  Probably should change the wording.

**Comment by narthollis** [comment]
It would be useful to include the action perfomed as well as the list of current subs, eg:

> Hello there ${user}
>
> You have been ${action} from ${author}
>
> Your  current subscriptions are now:
> ${subscriptions}
>
> To unsubscribe to any of these users, send a message that contains the word unsubscribe and a list of users, for example: unsubscribe /u/username /u/username2
> If I'm broke Contact user 'TheDarkLordSano' via PM or IRC.
> I have a wiki page
