### ISSUE TITLE
Posting on Old posts

### ISSUE THREAD

**Issue by TheDarkLordSano** [TheDarkLordSano/HFYBeetusBot#16]
Apparently there are cases were the bot can get stuck on trying to post to OLD content.

Whodathunkit.  We'll need some type of timeout on the "comment on old postings"

Maybe a check if it as in the past 4-6 months?

**Comment by narthollis** [comment]
That would seam like a reasonable approach. I would also check to see if
there is an API in praw to check if a post is archived

**Comment by TheDarkLordSano** [comment]
It should throw an exception and get caught and then skipped(Bot V1). Right now it is hitting something and the logs kick out the "Too many actions, waiting 1 minute".  This may not be an error in V2.

**Comment by TheDarkLordSano** [comment]
No longer seems to be an issue in Version 2.
